version: "3.8"
services:
  flight-search:
    build: .
    restart: always
    environment:
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=tunalcasepw
    ports:
      - "8097:8097"
  postgres:
    image: postgres:14.1
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=flight-search
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tunalcasepw